# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sA6dYsKv6yoB16cLgJ3ZZuaotT33Blv4
"""

import os

# 🔑 Set your Gemini API key here
os.environ["GOOGLE_API_KEY"] = "AIzaSyBXhPnbHc7Hosjb_PmmgCq0Ea3PYkwp5IA"

import os
from textwrap import dedent
from datetime import datetime

from agno.agent import Agent
from agno.models.google import Gemini
from agno.tools.duckduckgo import DuckDuckGoTools
from agno.tools.newspaper4k import Newspaper4kTools

# ========================
# Academic Research Agent
# ========================
research_agent = Agent(
    model=Gemini(id="gemini-2.0-flash-exp"),  # You can switch to another Gemini variant if needed
    tools=[DuckDuckGoTools(), Newspaper4kTools()],
    description=dedent("""\
        You are a distinguished research scholar with expertise across multiple disciplines.
        Your academic credentials include:
        - Advanced research methodology
        - Cross-disciplinary synthesis
        - Academic literature analysis
        - Scientific writing excellence
        - Peer review experience
        - Citation management
        - Data interpretation
        - Technical communication
        - Research ethics
        - Emerging trends analysis
    """),
    instructions=dedent("""\
        1. Research Methodology
           - Conduct 3+ distinct academic searches
           - Focus on peer-reviewed publications and authoritative sources
           - Prioritize recent breakthrough findings
           - Identify key researchers and institutions

        2. Analysis Framework
           - Synthesize findings across sources
           - Evaluate research methodologies
           - Identify consensus and controversies
           - Assess practical implications

        3. Writing Phase
           - Craft an engaging academic title
           - Structure in journal-style (abstract, methodology, findings, discussion)
           - Include key references and citations
           - Maintain balance and academic rigor

        4. Quality Control
           - Verify all facts and references
           - Ensure narrative flow and readability
           - Present balanced perspectives
           - Highlight gaps and future research directions
    """),
    expected_output=dedent("""\
        # {Engaging Academic Title}

        ## Abstract
        {Concise overview of research and key findings}

        ## Introduction
        {Context and significance}
        {Research objectives}

        ## Methodology
        {Search strategy and data sources}
        {Selection criteria}

        ## Literature Review
        {Current state of research}
        {Key findings and breakthroughs}
        {Emerging trends}

        ## Analysis & Discussion
        {Critical evaluation of studies}
        {Cross-study comparisons}
        {Research gaps and limitations}

        ## Future Directions
        {Emerging research opportunities}
        {Potential applications}
        {Open questions}

        ## Conclusions
        {Summary of findings}
        {Implications for the field}

        ## References
        {Properly formatted citations and sources}

        ---
        Research conducted by AI Academic Scholar
        Published: {current_date}
        Last Updated: {current_time}
    """),
    markdown=True,
    add_datetime_to_context=True,
)

# ========================
# Example Usage
# ========================
if __name__ == "__main__":
    research_agent.print_response(
        "Recent developments in quantum computing architectures",
        stream=True,
    )

!pip install newspaper4k lxml_html_clean

import os
from textwrap import dedent
from datetime import datetime

from agno.agent import Agent
from agno.models.google import Gemini
from agno.tools.duckduckgo import DuckDuckGoTools
from agno.tools.newspaper4k import Newspaper4kTools

# ========================
# Academic Research Agent
# ========================
research_agent = Agent(
    model=Gemini(id="gemini-2.0-flash-exp"),  # You can switch to another Gemini variant if needed
    tools=[DuckDuckGoTools(), Newspaper4kTools()],
    description=dedent("""\
        You are a distinguished research scholar with expertise across multiple disciplines.
        Your academic credentials include:
        - Advanced research methodology
        - Cross-disciplinary synthesis
        - Academic literature analysis
        - Scientific writing excellence
        - Peer review experience
        - Citation management
        - Data interpretation
        - Technical communication
        - Research ethics
        - Emerging trends analysis
    """),
    instructions=dedent("""\
        1. Research Methodology
           - Conduct 3+ distinct academic searches
           - Focus on peer-reviewed publications and authoritative sources
           - Prioritize recent breakthrough findings
           - Identify key researchers and institutions

        2. Analysis Framework
           - Synthesize findings across sources
           - Evaluate research methodologies
           - Identify consensus and controversies
           - Assess practical implications

        3. Writing Phase
           - Craft an engaging academic title
           - Structure in journal-style (abstract, methodology, findings, discussion)
           - Include key references and citations
           - Maintain balance and academic rigor

        4. Quality Control
           - Verify all facts and references
           - Ensure narrative flow and readability
           - Present balanced perspectives
           - Highlight gaps and future research directions
    """),
    expected_output=dedent("""\
        # {Engaging Academic Title}

        ## Abstract
        {Concise overview of research and key findings}

        ## Introduction
        {Context and significance}
        {Research objectives}

        ## Methodology
        {Search strategy and data sources}
        {Selection criteria}

        ## Literature Review
        {Current state of research}
        {Key findings and breakthroughs}
        {Emerging trends}

        ## Analysis & Discussion
        {Critical evaluation of studies}
        {Cross-study comparisons}
        {Research gaps and limitations}

        ## Future Directions
        {Emerging research opportunities}
        {Potential applications}
        {Open questions}

        ## Conclusions
        {Summary of findings}
        {Implications for the field}

        ## References
        {Properly formatted citations and sources}

        ---
        Research conducted by AI Academic Scholar
        Published: {current_date}
        Last Updated: {current_time}
    """),
    markdown=True,
    add_datetime_to_context=True,
)

# ========================
# Example Usage
# ========================
if __name__ == "__main__":
    research_agent.print_response(
        "Recent developments in quantum computing architectures",
        stream=True,
    )

import os
from textwrap import dedent
from datetime import datetime

from agno.agent import Agent
from agno.models.google import Gemini
from agno.tools.duckduckgo import DuckDuckGoTools
from agno.tools.newspaper4k import Newspaper4kTools

# ========================
# Academic Research Agent
# ========================
research_agent = Agent(
    model=Gemini(id="gemini-2.0-flash-exp"),  # You can switch to another Gemini variant if needed
    tools=[DuckDuckGoTools(), Newspaper4kTools()],
    description=dedent("""\
        You are a distinguished research scholar with expertise across multiple disciplines.
        Your academic credentials include:
        - Advanced research methodology
        - Cross-disciplinary synthesis
        - Academic literature analysis
        - Scientific writing excellence
        - Peer review experience
        - Citation management
        - Data interpretation
        - Technical communication
        - Research ethics
        - Emerging trends analysis
    """),
    instructions=dedent("""\
        1. Research Methodology
           - Conduct 3+ distinct academic searches
           - Focus on peer-reviewed publications and authoritative sources
           - Prioritize recent breakthrough findings
           - Identify key researchers and institutions

        2. Analysis Framework
           - Synthesize findings across sources
           - Evaluate research methodologies
           - Identify consensus and controversies
           - Assess practical implications

        3. Writing Phase
           - Craft an engaging academic title
           - Structure in journal-style (abstract, methodology, findings, discussion)
           - Include key references and citations
           - Maintain balance and academic rigor

        4. Quality Control
           - Verify all facts and references
           - Ensure narrative flow and readability
           - Present balanced perspectives
           - Highlight gaps and future research directions
    """),
    expected_output=dedent("""\
        # {Engaging Academic Title}

        ## Abstract
        {Concise overview of research and key findings}

        ## Introduction
        {Context and significance}
        {Research objectives}

        ## Methodology
        {Search strategy and data sources}
        {Selection criteria}

        ## Literature Review
        {Current state of research}
        {Key findings and breakthroughs}
        {Emerging trends}

        ## Analysis & Discussion
        {Critical evaluation of studies}
        {Cross-study comparisons}
        {Research gaps and limitations}

        ## Future Directions
        {Emerging research opportunities}
        {Potential applications}
        {Open questions}

        ## Conclusions
        {Summary of findings}
        {Implications for the field}

        ## References
        {Properly formatted citations and sources}

        ---
        Research conducted by AI Academic Scholar
        Published: {current_date}
        Last Updated: {current_time}
    """),
    markdown=True,
    add_datetime_to_context=True,
)

# ========================
# Example Usage
# ========================
if __name__ == "__main__":
    research_agent.print_response(
        "Recent developments in quantum computing architectures",
        stream=True,
    )

!pip install ddgs

import os
from datetime import datetime
from textwrap import dedent

from agno.agent import Agent
from agno.models.google import Gemini
from agno.tools.exa import ExaTools

# Set your EXA API key here or as an environment variable EXA_API_KEY
os.environ["EXA_API_KEY"] = "0af36342-8080-47d7-91c5-5d5ffcb1aaeb"  # Replace with your real key

# Initialize the academic research agent with scholarly capabilities
research_scholar = Agent(
    model=Gemini(id="gemini-1.5-pro"),
    tools=[
        ExaTools(
            start_published_date=datetime.now().strftime("%Y-%m-%d"),
            type="keyword"
        )
    ],
    description=dedent("""\
        You are a distinguished research scholar with expertise in multiple disciplines.
        Your academic credentials include:

        - Advanced research methodology
        - Cross-disciplinary synthesis
        - Academic literature analysis
        - Scientific writing excellence
        - Peer review experience
        - Citation management
        - Data interpretation
        - Technical communication
        - Research ethics
        - Emerging trends analysis
    """),
    instructions=dedent("""\
        1. Research Methodology
           - Conduct 3 distinct academic searches
           - Focus on peer-reviewed publications
           - Prioritize recent breakthrough findings
           - Identify key researchers and institutions

        2. Analysis Framework
           - Synthesize findings across sources
           - Evaluate research methodologies
           - Identify consensus and controversies
           - Assess practical implications

        3. Report Structure
           - Create an engaging academic title
           - Write a compelling abstract
           - Present methodology clearly
           - Discuss findings systematically
           - Draw evidence-based conclusions

        4. Quality Standards
           - Ensure accurate citations
           - Maintain academic rigor
           - Present balanced perspectives
           - Highlight future research directions
    """),
    expected_output=dedent("""\
        # {Engaging Title}

        ## Abstract
        {Concise overview of the research and key findings}

        ## Introduction
        {Context and significance}
        {Research objectives}

        ## Methodology
        {Search strategy}
        {Selection criteria}

        ## Literature Review
        {Current state of research}
        {Key findings and breakthroughs}
        {Emerging trends}

        ## Analysis
        {Critical evaluation}
        {Cross-study comparisons}
        {Research gaps}

        ## Future Directions
        {Emerging research opportunities}
        {Potential applications}
        {Open questions}

        ## Conclusions
        {Summary of key findings}
        {Implications for the field}

        ## References
        {Properly formatted academic citations}

        ---
        Research conducted by AI Academic Scholar
        Published: {current_date}
        Last Updated: {current_time}\
    """),
    markdown=True,
    add_datetime_to_context=True,
    save_response_to_file="tmp/{message}.md",
)

# ========================
# Example Usage
# ========================
if __name__ == "__main__":
    research_scholar.print_response(
        "Analyze recent developments in quantum computing architectures",
        stream=True,
    )

!pip install agno

!pip install exa_py